name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        id: playwright-tests
        run: pnpm test-e2e:trace && pnpm test-ct:trace
      - name: Update Snapshots
        if: failure() && steps.playwright-tests.conclusion == 'failure'
        run: pnpm test-e2e --update-snapshots && pnpm test-ct --update-snapshots
      - uses: actions/upload-artifact@v4
        if: always() && !cancelled()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - uses: actions/upload-artifact@v4
        if: always() && !cancelled()
        with:
          name: snapshots
          path: '**/__snapshots__'
          retention-days: 30
