name: Playwright VRT
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        id: playwright-tests
        run: pnpm test-e2e:vrt && pnpm test-ct:vrt
      - name: Update Snapshots
        if: failure() && steps.playwright-tests.conclusion == 'failure'
        run: pnpm test-e2e:vrt --update-snapshots && pnpm test-ct:vrt --update-snapshots
      - uses: actions/upload-artifact@v4
        if: always() && !cancelled()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - uses: actions/upload-artifact@v4
        if: always() && !cancelled()
        with:
          name: snapshots
          path: '**/__snapshots__'
          retention-days: 30
  upload-artifact-to-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Upload Artifact to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
