name: Playwright VRT
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      # テスト実行
      - name: Run Playwright tests
        id: playwright-tests
        run: pnpm test-e2e:vrt ; pnpm test-ct:vrt
      # playwright-reportをartifactsに保存
      - name: Upload Artifacts - Playwright Report
        uses: actions/upload-artifact@v4
        if: always() && !cancelled()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # GitHub Pages用のartifactsを保存する
      # GitHub Pages 用のindex.html を作成
      - name: Create index.html
        if: always() && !cancelled()
        run: |
          ls -la
          echo "Checking playwright-report directory:"
          ls -la playwright-report || echo "playwright-report directory does not exist yet"
          cat > playwright-report/index.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
            <title>Playwright Test Reports</title>
            <style>
              body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
              h1 { color: #333; }
              .links { margin-top: 20px; }
              .links a { display: block; margin: 10px 0; padding: 10px; background-color: #f0f0f0;
                        text-decoration: none; color: #333; border-radius: 4px; }
              .links a:hover { background-color: #e0e0e0; }
            </style>
          </head>
          <body>
            <h1>Playwright Test Reports</h1>
            <div class="links">
              <a href="/e2e">E2E Tests Report</a>
              <a href="/ct">Component Tests Report</a>
            </div>
          </body>
          </html>
          EOL

      # artifactsを保存
      - name: Upload Artifacts - Pages Artifact
        uses: actions/upload-pages-artifact@v3
        if: always() && !cancelled()
        with:
          path: playwright-report/

      # actual snapshots を作成
      - name: Update Snapshots
        if: failure() && steps.playwright-tests.conclusion == 'failure'
        run: pnpm test-e2e:vrt --update-snapshots --reporter=null && pnpm test-ct:vrt --update-snapshots --reporter=null

      # actual snapshots をartifactsに保存
      - name: Upload Artifacts - Actual Snapshots
        uses: actions/upload-artifact@v4
        if: always() && !cancelled()
        with:
          name: actual-snapshots
          path: __snapshots__/
          retention-days: 30
  upload-artifact-to-pages:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: test
    if: always() && !cancelled()
    steps:
      - name: Upload PagesArtifact to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
